wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="wiki"),
    path("search/", views.search_page, name="search"),
    path("create/", views.new_page, name="create"),
    path("save/", views.save_page, name="save"),
    path("random/", views.random_page, name="random"),
    path("<str:title>/", views.get_page, name="title"),
    path("<str:title>/edit", views.edit_page, name="edit"),
    
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/forms.py
from django import forms

class SearchForm(forms.Form):
    search = forms.CharField(label="Search",required= False, widget=forms.TextInput(attrs={'placeholder':'Search Encyclopedia'}))

markdown = forms.CharField(
    label='Markdown content',
    required=False,
    widget=forms.Textarea(attrs={
        'size': 50,
        'placeholder': 'Enter markdown content...',

}))

class BaseForm(forms.Form):
    title = forms.CharField(label='Title', required=True)
    content = markdown


class EditForm(forms.Form):
    title = forms.CharField(label='Title', required=False, widget=forms.HiddenInput)
    content = markdown

wiki/encyclopedia/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from . import util,forms
from random import choice
from django.urls import reverse
form = forms.SearchForm()

def index(request):

    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "form": form
    })

def get_page(request, title):

    page = util.get_entry(title)   

    if page is None:
         return render(request, "encyclopedia/error404.html", {
            "form": form
        })
    
    return render(request, "encyclopedia/title.html", {
        "title": title,
        "content": page,
        "form": form
    })

def new_page(request):
    if request.method == "POST":
        new_form = forms.BaseForm(request.POST)
        if new_form.is_valid():
            title = new_form.cleaned_data["title"]          
            content = new_form.cleaned_data["content"]            
            for entry in util.list_entries():
                if title.lower() == entry.lower(): 
                    return render(request, "encyclopedia/new.html", {
                        "new_form": forms.BaseForm(),
                        "form": form,
                        "error409": entry,
                    })
            util.save_entry(title, content)
            return HttpResponseRedirect(reverse("wiki:title", kwargs={'title': title}))   
    return render(request, "encyclopedia/new.html", {
        "new_form": forms.BaseForm(),
        "form": form
    })

def edit_page(request, title):       
    content = util.get_entry(title)
    edit_form = forms.EditForm(initial={'title': title,'content': content})
    if edit_form.is_valid():
        return render(request, "encyclopedia/edit.html", {
            "title": title,
            "form": form,
            "edit_form": edit_form,
        })
    else:
        return render(request, "encyclopedia/edit.html", {
            "title": title,
            "form": form,
            "edit_form": edit_form,
        })

def save_page(request):
    edit_form = forms.EditForm(request.POST)
    if edit_form.is_valid():
        title = edit_form.cleaned_data["title"]
        content = edit_form.cleaned_data["content"]        
        util.save_entry(title, content)
        return HttpResponseRedirect(reverse("wiki:title", kwargs={'title': title}))

    else:
        return render(request, "encyclopedia/edit.html",{
            "form":form,
            "edit_form":edit_form
            
        })

def random_page(request):    
    return HttpResponseRedirect(reverse("wiki:title", kwargs={'title': choice(util.list_entries())}))

def search_page(request):
    if request.method == "GET":
        form = forms.SearchForm(request.GET)
        if form.is_valid():
            search = form.cleaned_data["search"].lower()
            entries = util.list_entries()

            pages_found = [page for page in entries if search in page.lower()]

            if len(pages_found)==0:
                return render(request, "encyclopedia/search.html", {
                    "error409": True,
                    "form": form
                })
            
            elif len(pages_found) == 1 and pages_found[0].lower() == search:
                
                title = pages_found[0]
                return HttpResponseRedirect(reverse("wiki:title", kwargs={'title': title}))

            else:
                title = [page for page in pages_found if search == page.lower()]
                if len(title)>0:
                    return get_page(request, title[0])
                else:
                    return render(request, "encyclopedia/search.html", {
                    "found": pages_found,
                    "form": form
                })

        else: 
            return index(request)
    
    return index(request)

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}:
  {{ title }} - Edit
{% endblock %}

{% block body %}
    <h2>{{title}}</h2>

    <form action="{% url 'wiki:save'   %}" method="POST">
      {% csrf_token %}
      {{ edit_form }}
      <input type="submit" id="createpage">
    </form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/error404.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ ERROR404 }}
{% endblock %}

{% block body %}
    <h1 class="text-warning">ERROR 404: Page was not found.</h1>  

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'wiki:title' title=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="author" content="VincVader">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Wiki{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:search' %}" method='GET' class="search">
                    {{ form }}
                    <input id="search" type="submit" value="Search">
                </form>
                <div>
                    <a href="/wiki/">Home</a>
                </div>
                <div>
                    <a href="/wiki/create/">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-8">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}:
    New Page 
{% endblock %}

{% block body %}
    <h1>Create new page</h1>
    {% if error409 %}
    <h4 class="text-warning">Page already exists with similar title: "{{ error409 }}"</h4>
    {% endif %}

    <form action="{% url 'wiki:create' %}" method="post">
      {% csrf_token %}
      {{ new_form }}
      <input type="submit" value="Create New Page">
    </form>


    

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search
{% endblock %}

{% block body %}

<h1> Search results </h1>
<ul id ="search_result">
  {% if error409 %}
  <h2 class="text-warning">No matching page found</h2>
  {% endif %}
    
    {% for page in found %}
      <li>
        <a href= "{% url 'wiki:title' title=page %}">{{page}}</a>
      </li>
    {% endfor %}
</ul>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/title.html
{% extends "encyclopedia/layout.html" %}
{% block title %}: {{title}}

{% endblock %}

{% block body %}

<form action="{% url 'wiki:edit' title=title%}" method="POST">
    {% csrf_token %}
    
    {% load md2 %}
    {{ content|markdown|safe }}
    
    <button type="submit" name="edit" value="{{title}}" id="edit">Edit page</button>

</form>
{% endblock %}